name = "jeswin-portfolio"
compatibility_date = "2026-10-03"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "jeswin-portfolio-db"
database_id = "31d3759e-1b5d-4c1c-94a1-fd94341b692e"
# Cloudflare D1 binding configured
